
name: run Web tests
run-name: On Push - tests workflow run
on: [push]

jobs:
  web-test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:  
      - name: Checkout
        uses: actions/checkout@v3   
      - run: echo " Teste workflow ROBOT"

      - name: Install Python 3.10 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Install Node.js 20.15
        uses: actions/setup-node@v3
        with:
          node-version: '19.1' 


      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install playwright/test
          sudo npx playwrigth install-deps
          rfbrowser init


      - name: run Web tests 
        run: |
          robot -d./results -v HEADLESS:true -v BROWSER:chromium tests


      - name: upload tests results
        if: always()
        uses: actions/upload-artifact@v3
        with: 
          name: results-chromium
          path: ./results
          if-no-files-found: ignore   #não quebrar os testes por falha na esteira
          retention-days: 2


        
      - name: download tests results
        if: always()
        uses: actions/download-artifact@v1
        with:
          name: results-chromium

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.1
        with:
          report_path: results-chromium
          gh_access_token: ${{ secrets.GITHUB_TOKEN}}
          show_passed_tests: false     



